import{S as l,i as c}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const u="44070637-4c17cd33bb35071a705149900";function f(e,o){const s=new URLSearchParams({key:u,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${s}`).then(n=>{if(!n.ok)throw new Error(n.status);return n.json()}).then(o).catch(n=>console.log(n))}const d=new l(".gallery a",{captionsData:"alt",captionDelay:250});function m(){return'<div class="loader"></div>'}function p(){c.warning({title:"Ooops",position:"topRight"})}function h(){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function g(e){return`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" class="foto" height="148" width="360">
      <div class="info" >
        <p class="icon">Likes: ${e.likes} </p>
        <p class="icon">Views: ${e.views}</p>
        <p class="icon">Comments: ${e.comments}</p>
        <p class="icon">Downloads: ${e.downloads}</p>
      </div>
    </a>`}function y(e){return e.map(o=>g(o)).join("")}const L=document.querySelector(".form"),a=document.querySelector(".gallery");L.addEventListener("submit",e=>{e.preventDefault();const o=e.target.elements.searchInput.value.trim();if(o===""){p();return}a.innerHTML=m(),f(o,w)});function w(e){if(!e.total&&e.total==0){h(),a.innerHTML="";return}const o=e.hits;console.log("response",e);const s=y(o);a.innerHTML=s,d.refresh()}
//# sourceMappingURL=commonHelpers.js.map
